//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoznaniciWEBAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Osoba
    {
        public int Id { get; set; }
        public string JMBG { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<short> Visina { get; set; }
        [Display(Name = "Težina")]
        public Nullable<short> Tezina { get; set; }
        [Display(Name = "Boja očiju")]
        public string BojaOciju { get; set; }
        public string Telefon { get; set; }
        [Display(Name = "E pošta")]
        public string E_posta { get; set; }
        public Nullable<System.DateTime> Rodjendan { get; set; }
        public string Adresa { get; set; }
        [Display(Name = "Prebivalište")]
        public string Prebivaliste { get; set; }
    }
}
